name: Deploy to EC2

on:
  push:
    branches:
      - main  # O pipeline roda sempre que houver um push para a branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # versão do Node.js que você está usando

    - name: Install dependencies
      run: |
        npm install

    - name: Build the project
      run: |
        npm run build

    - name: Deploy to EC2
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      run: |
        # Defina a variável de ambiente para o IP da EC2
        EC2_PUBLIC_IP="your.ec2.public.ip"
        
        # Copiar a chave privada para a instância
        echo "$DEPLOY_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Usar SCP para copiar os arquivos para a instância EC2
        scp -i private_key.pem -o StrictHostKeyChecking=no -r build/* ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/sustentare-web/build

        # Conectar via SSH e rodar o deploy
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
          cd /home/ubuntu/sustentare-web
          git pull origin main
          npm install
          npm run build
          pm2 restart sustentare-web || pm2 start build/ --name sustentare-web
        EOF
