name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint (optional, only to check issues)
      run: npm run lint

    - name: Build the project
      run: |
        CI=false npm run build

    - name: Copy deploy.sh to the EC2 server and run it
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        # Salvar a chave privada corretamente
        echo "$DEPLOY_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem

        # Agora execute o script deploy.sh usando o SSH
        scp -i private_key.pem -o StrictHostKeyChecking=no -r build/* ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/sustentare-web/build

        # Conectar via SSH e rodar o deploy
        ssh -i private_key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
          cd /home/ubuntu/sustentare-web
          git pull origin main
          npm install
          npm run build
          pm2 restart sustentare-web || pm2 start build/ --name sustentare-web
        EOF
