name: Deploy to EC2

on:
  push:
    branches:
      - main  # O pipeline roda sempre que houver um push para a branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install
        npm install --save-dev @babel/plugin-proposal-private-property-in-object  # Instala a dependência faltante

    - name: Run ESLint (optional, only to check issues)
      run: |
        npm run lint  # Caso tenha um script de lint no package.json, rode ele antes de buildar

    - name: Build the project
      run: |
        CI=false npm run build  # Desativa o tratamento de erros como falha no build, caso necessário

    - name: Copy deploy.sh to the EC2 server and run it
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        echo "$DEPLOY_PRIVATE_KEY" > deploy.sh
        chmod +x deploy.sh
        ./deploy.sh
