name: Deploy to EC2

on:
  push:
    branches:
      - main  # O pipeline roda sempre que houver um push para a branch main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Create and run deploy.sh script
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        # Criar o script deploy.sh com os comandos de deploy
        echo "#!/bin/bash
        set -xe

        scp -i \"\$DEPLOY_PRIVATE_KEY\" -o StrictHostKeyChecking=no -r build/* ubuntu@\$EC2_PUBLIC_IP:/home/ubuntu/sustentare-web/build

        ssh -i \"\$DEPLOY_PRIVATE_KEY\" -o StrictHostKeyChecking=no ubuntu@\$EC2_PUBLIC_IP << 'EOF'
          cd /home/ubuntu/sustentare-web
          git pull origin main
          npm install
          npm run build
          pm2 restart sustentare-web || pm2 start build/ --name sustentare-web
        EOF" > deploy.sh

        chmod +x deploy.sh
        ./deploy.sh
