name: Deploy para EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fazer checkout do código
      uses: actions/checkout@v3

    - name: Configurar o Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependências
      run: npm install

    - name: Rodar ESLint (opcional, apenas para verificar problemas)
      run: npm run lint

    - name: Construir o projeto
      run: |
        CI=false npm run build

    - name: Copiar o deploy.sh para o servidor EC2 e executá-lo
      env:
        DEPLOY_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
      run: |
        # Salvar a chave privada corretamente
        echo "$DEPLOY_PRIVATE_KEY" > public_instance_key.pem
        chmod 600 public_instance_key.pem

        # Copiar os arquivos para a instância EC2
        scp -i public_instance_key.pem -o StrictHostKeyChecking=no -r build/* ubuntu@$EC2_PUBLIC_IP:/home/ubuntu/sustentare-web/build

        # Conectar via SSH e rodar o deploy
        ssh -i public_instance_key.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
          # Instalar o pm2
          sudo npm install -g pm2

          # Iniciar o servidor com npm start (para ambiente de produção, considere alternativas)
          cd /home/ubuntu/sustentare-web
          git pull origin main
          npm install
          npm run build
          npm start  # Usar para rodar o servidor de desenvolvimento (não recomendado em produção)
        EOF
